name: Release

on:
  push:
    branches: [master, main]
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download Java
      id: download-java
      uses: typelevel/download-java@v1
      with:
        distribution: temurin
        java-version: 8

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: jdkfile
        java-version: 8
        jdkFile: ${{ steps.download-java.outputs.jdkFile }}

    - name: Set up GPG
      run: |
        mkdir ~/.gnupg && chmod 700 ~/.gnupg
        echo use-agent >> ~/.gnupg/gpg.conf
        echo pinentry-mode loopback >> ~/.gnupg/gpg.conf
        echo allow-loopback-pinentry >> ~/.gnupg/gpg-agent.conf
        chmod 600 ~/.gnupg/*
        echo RELOADAGENT | gpg-connect-agent
        echo $PGP_SECRET | base64 --decode | gpg --import --no-tty --batch --yes
      env:
        PGP_SECRET: ${{secrets.PGP_SECRET}}

    - name: Run tests
      run: |
        sbt headerCheck
        sbt ^test
        sbt ^mimaReportBinaryIssues

    - name: Publish release
      run: |
        export GPG_TTY=$(tty)
        sbt ci-release
      env:
        CI_RELEASE: '^publishSigned'
        CI_SNAPSHOT_RELEASE: '^publish'
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
